name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  tests:
  
    name: Test on ${{matrix.container }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: [' qgis/qgis:latest', 'qgis/qgis:release-3_22', 'qgis/qgis:release-3_20', 'qgis/qgis:release-3_18']

    container: ${{ matrix.container }}
    
    steps:
    
    - name: Checkout Project
      uses: actions/checkout@v2.3.4
        
    - name: Unit Tests
      env:
        DISPLAY: :99
      run: |
        xvfb-run qgis_testrunner.sh tests.run_tests.run_all
