name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  tests:
  
    name: Test on ${{matrix.container }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: [' qgis/qgis:latest', 'qgis/qgis:release-3_22', 'qgis/qgis:release-3_24', 'qgis/qgis:release-3_26', 'qgis/qgis:release-3_28', 'qgis/qgis@sha256:a05df35259317e3457d4cdc73f0aabf0623f1e7a8257c56bff10b041ded3dce3']

    container: ${{ matrix.container }}
    
    steps:
    
    - name: Checkout Project
      uses: actions/checkout@v3
        
    - name: Unit Tests
      env:
        DISPLAY: :99
      run: |
        xvfb-run qgis_testrunner.sh tests.run_tests.run_all
